<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="../static/style/modal.css">
    <title>Document</title>
</head>
<body>
<div  id="modal" >
    <button data-btn="price">click</button>

</div>

<script src="../js/base.js"></script>
<script src="../js/plugins/modal.js"></script>
<script src="../js/index.js"></script>
</body>
</html>